const certificateFiles = [
  "CompTIA Security  ce certificate.pdf",
  "Cyber Security (Short Course) Certificate.pdf",
  "Data_ScienceZTM.jpg",
  "Dion acadamy comptia security .pdf",
  "SOC.pdf",
  "TABGCSp1.pdf",
  "TBGTPHS.pdf",
  "UC-09f44636-e5c7-488e-ac81-9ac620af0779.pdf",
  "ZTMPython.jpg",
  "ZTM_ethical_hacking_course.pdf",
  "golang cert.jpg",
  "sact.pdf",
  "CompTIA Security  ce certificate.jpg",
  "Cyber Security (Short Course) Certificate.jpg",
  "Dion acadamy comptia security .jpg",
  "SOC.jpeg",
  "TABGCSp1.jpeg",
  "TBGTPHS.jpeg",
  "UC-09f44636-e5c7-488e-ac81-9ac620af0779.jpeg",
  "ZTM_ethical_hacking_course.jpeg",
  "sact.jpeg",
  "z-sec course cert.jpg",
];
