const artImages = [
  "At the end of everything.webp",
  "EVEREST.webp",
  "STEPHAN HAWKING.webp",
  "abberation.webp",
  "armani.webp",
  "damianM.webp",
  "displace.webp",
  "final.webp",
  "inthedark.webp",
  "kings.webp",
  "momento.webp",
  "starewaytoheaven.webp",
  "tears in the rain.webp",
  "ubridled.webp",
  "weallcastshadows.webp",
];
